"""
报告生成模块 - 生成HTML邮件
"""

import re
from datetime import datetime

def markdown_to_html(text: str) -> str:
    """将Markdown转换为HTML"""
    if not text:
        return ""
    
    # 处理代码块（防止内部内容被错误处理）
    text = re.sub(r'```(\w*)\n(.*?)```', r'<pre><code>\2</code></pre>', text, flags=re.DOTALL)
    
    # 处理标题
    text = re.sub(r'^# (.+)$', r'<h1>\1</h1>', text, flags=re.MULTILINE)
    text = re.sub(r'^## (.+)$', r'<h2>\1</h2>', text, flags=re.MULTILINE)
    text = re.sub(r'^### (.+)$', r'<h3>\1</h3>', text, flags=re.MULTILINE)
    
    # 处理粗体
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    
    # 处理斜体
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    
    # 处理链接 [text](url)
    text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2" style="color:#0066cc;">\1</a>', text)
    
    # 处理独立URL
    text = re.sub(
        r'(?<!["\'>=/])(?<![a-zA-Z])(https?://[^\s<>\'")\]]+)',
        r'<a href="\1" style="color:#0066cc;">\1</a>',
        text
    )
    
    # 处理无协议URL
    text = re.sub(
        r'(?<![/"\'>@=a-zA-Z0-9])((?:www\.)?[a-zA-Z0-9][-a-zA-Z0-9]*\.(?:com|org|net|edu|gov|io|ai|dev)[^\s<>\'")\]]*)',
        r'<a href="https://\1" style="color:#0066cc;">\1</a>',
        text
    )
    
    # 处理引用块
    text = re.sub(r'^> (.+)$', r'<blockquote>\1</blockquote>', text, flags=re.MULTILINE)
    
    # 合并连续blockquote
    text = re.sub(r'</blockquote>\n<blockquote>', '<br>', text)
    
    # 处理无序列表
    text = re.sub(r'^- (.+)$', r'<li>\1</li>', text, flags=re.MULTILINE)
    text = re.sub(r'^• (.+)$', r'<li>\1</li>', text, flags=re.MULTILINE)
    
    # 处理有序列表
    text = re.sub(r'^(\d+)\. (.+)$', r'<li>\2</li>', text, flags=re.MULTILINE)
    
    # 包装列表项
    text = re.sub(r'((?:<li>.*?</li>\n?)+)', r'<ul>\1</ul>', text)
    
    # 处理分隔线
    text = re.sub(r'^---+$', r'<hr style="border:none;border-top:1px solid #e0e0e0;margin:25px 0;">', text, flags=re.MULTILINE)
    
    # 处理段落（非标签开头的行）
    lines = text.split('\n')
    result = []
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if not re.match(r'^<[a-zA-Z]', line):
            line = f'<p>{line}</p>'
        result.append(line)
    
    return '\n'.join(result)


def generate_html_report(briefing) -> str:
    """生成HTML邮件报告"""
    
    content_html = markdown_to_html(briefing.full_content)
    
    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Research Intelligence Briefing | {briefing.date}</title>
</head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Noto Sans SC',sans-serif;line-height:1.8;color:#1a1a2e;background:#f5f5f5;">
    <div style="max-width:700px;margin:0 auto;background:#ffffff;">
        
        <!-- Header -->
        <div style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 50%,#0f3460 100%);padding:35px 40px;color:white;">
            <h1 style="margin:0;font-size:26px;font-weight:700;">📊 Research Intelligence Briefing</h1>
            <p style="margin:8px 0 0;font-size:14px;opacity:0.85;">全球经济与AI技术深度研究日报</p>
            <p style="margin:12px 0 0;font-size:13px;opacity:0.7;">{briefing.date}</p>
        </div>
        
        <!-- Content -->
        <div style="padding:35px 40px;">
            <style>
                h1 {{ font-size:22px; color:#1a1a2e; margin:30px 0 15px; padding-bottom:10px; border-bottom:2px solid #e9ecef; }}
                h1:first-child {{ margin-top:0; }}
                h2 {{ font-size:18px; color:#16213e; margin:25px 0 12px; }}
                h3 {{ font-size:16px; color:#333; margin:20px 0 10px; }}
                p {{ margin:12px 0; font-size:15px; color:#333; }}
                strong {{ color:#1a1a2e; }}
                ul {{ margin:15px 0; padding-left:25px; }}
                li {{ margin:8px 0; font-size:14px; color:#444; }}
                blockquote {{ background:#f8f9fa; border-left:4px solid #ffc107; padding:15px 20px; margin:15px 0; font-style:italic; color:#555; }}
                a {{ color:#0066cc; text-decoration:underline; }}
                hr {{ border:none; border-top:1px solid #e0e0e0; margin:25px 0; }}
                pre {{ background:#f4f4f4; padding:15px; overflow-x:auto; border-radius:5px; }}
                code {{ font-family:monospace; font-size:13px; }}
            </style>
            {content_html}
        </div>
        
        <!-- Footer -->
        <div style="background:#f8f9fa;padding:25px 40px;text-align:center;border-top:1px solid #e9ecef;">
            <p style="margin:0;font-size:12px;color:#6c757d;">Generated by AI Research Assistant</p>
            <p style="margin:5px 0 0;font-size:11px;color:#999;">Sources: BBC, Reuters, MIT Tech Review, arXiv, and more</p>
        </div>
        
    </div>
</body>
</html>"""
    
    return html
